[package]
name = "time"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true
serde_json.workspace = true
serde.workspace = true
schemars.workspace = true
shared.workspace = true
chrono.workspace = true
